/* A parser generated by PackCC 3.1.0 */

#ifndef PCC_INCLUDED_PHORAY_H
#define PCC_INCLUDED_PHORAY_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct lumos_context_tag lumos_context_t;

lumos_context_t *lumos_create(void *auxil);
int lumos_parse(lumos_context_t *ctx, int *ret);
void lumos_destroy(lumos_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_PHORAY_H */
